### ISSUE TITLE
The training model

### ISSUE THREAD

**Issue by nkhdiscovery** [mahsaayi/Corrupted-Character-Detection#1]
Dear Mahsa,
Would you please add the training model? There is no way to test your code without it.

**Comment by mahsaayi** [comment]
Hello Navid, 
The file added and here is some example images for the test. @nkhdiscovery 

![571052761_162995911](https://user-images.githubusercontent.com/8656526/35553694-2e435ac8-05ae-11e8-88f5-c5d3ecf797ab.jpg)
![571052771_472812566](https://user-images.githubusercontent.com/8656526/35553696-2e69cb04-05ae-11e8-83c5-91988ba65626.jpg)
![571052817_843221188](https://user-images.githubusercontent.com/8656526/35553697-2e92bb9a-05ae-11e8-8487-c52fc9039994.jpg)
![571052827_163217117](https://user-images.githubusercontent.com/8656526/35553698-2eb96236-05ae-11e8-8af8-509f7c22c143.jpg)
![571052848_333059399](https://user-images.githubusercontent.com/8656526/35553699-2ede58a2-05ae-11e8-9fa5-3053af470f22.jpg)

**Comment by mahsa-shams** [comment]
Hello Navid,
The file added and here are some example images for the test. @nkhdiscovery
![572376388_930267338](https://user-images.githubusercontent.com/8656526/35553815-a2ed6ab2-05ae-11e8-8655-43c66f15f7be.jpg)
![572376432_891551714](https://user-images.githubusercontent.com/8656526/35553816-a31249ae-05ae-11e8-91e1-7dda75c7fb21.jpg)
![572376487_592819311](https://user-images.githubusercontent.com/8656526/35553818-a3392452-05ae-11e8-84e9-9a913a48ab42.jpg)
![572376584_312985555](https://user-images.githubusercontent.com/8656526/35553819-a35c3a96-05ae-11e8-8b8a-fce86244c67e.jpg)
![572376646_462815188](https://user-images.githubusercontent.com/8656526/35553820-a37feb94-05ae-11e8-9921-81f90e80d188.jpg)

**Comment by nkhdiscovery** [comment]
Thanks a lot for your quick response!
I close the issue then.
